/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TeamRouteImport } from './routes/team'
import { Route as PartnersRouteImport } from './routes/partners'
import { Route as NewsRouteImport } from './routes/news'
import { Route as JoinRouteImport } from './routes/join'
import { Route as ImpactRouteImport } from './routes/impact'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as EventsRouteImport } from './routes/events'
import { Route as DonateRouteImport } from './routes/donate'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CausesRouteImport } from './routes/causes'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EventsSlugRouteImport } from './routes/events.$slug'
import { Route as CausesSlugRouteImport } from './routes/causes.$slug'

const TeamRoute = TeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnersRoute = PartnersRouteImport.update({
  id: '/partners',
  path: '/partners',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsRoute = NewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinRoute = JoinRouteImport.update({
  id: '/join',
  path: '/join',
  getParentRoute: () => rootRouteImport,
} as any)
const ImpactRoute = ImpactRouteImport.update({
  id: '/impact',
  path: '/impact',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const DonateRoute = DonateRouteImport.update({
  id: '/donate',
  path: '/donate',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CausesRoute = CausesRouteImport.update({
  id: '/causes',
  path: '/causes',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsSlugRoute = EventsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => EventsRoute,
} as any)
const CausesSlugRoute = CausesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => CausesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/causes': typeof CausesRouteWithChildren
  '/contact': typeof ContactRoute
  '/donate': typeof DonateRoute
  '/events': typeof EventsRouteWithChildren
  '/faq': typeof FaqRoute
  '/impact': typeof ImpactRoute
  '/join': typeof JoinRoute
  '/news': typeof NewsRoute
  '/partners': typeof PartnersRoute
  '/team': typeof TeamRoute
  '/causes/$slug': typeof CausesSlugRoute
  '/events/$slug': typeof EventsSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/causes': typeof CausesRouteWithChildren
  '/contact': typeof ContactRoute
  '/donate': typeof DonateRoute
  '/events': typeof EventsRouteWithChildren
  '/faq': typeof FaqRoute
  '/impact': typeof ImpactRoute
  '/join': typeof JoinRoute
  '/news': typeof NewsRoute
  '/partners': typeof PartnersRoute
  '/team': typeof TeamRoute
  '/causes/$slug': typeof CausesSlugRoute
  '/events/$slug': typeof EventsSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/causes': typeof CausesRouteWithChildren
  '/contact': typeof ContactRoute
  '/donate': typeof DonateRoute
  '/events': typeof EventsRouteWithChildren
  '/faq': typeof FaqRoute
  '/impact': typeof ImpactRoute
  '/join': typeof JoinRoute
  '/news': typeof NewsRoute
  '/partners': typeof PartnersRoute
  '/team': typeof TeamRoute
  '/causes/$slug': typeof CausesSlugRoute
  '/events/$slug': typeof EventsSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/causes'
    | '/contact'
    | '/donate'
    | '/events'
    | '/faq'
    | '/impact'
    | '/join'
    | '/news'
    | '/partners'
    | '/team'
    | '/causes/$slug'
    | '/events/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/causes'
    | '/contact'
    | '/donate'
    | '/events'
    | '/faq'
    | '/impact'
    | '/join'
    | '/news'
    | '/partners'
    | '/team'
    | '/causes/$slug'
    | '/events/$slug'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/causes'
    | '/contact'
    | '/donate'
    | '/events'
    | '/faq'
    | '/impact'
    | '/join'
    | '/news'
    | '/partners'
    | '/team'
    | '/causes/$slug'
    | '/events/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  CausesRoute: typeof CausesRouteWithChildren
  ContactRoute: typeof ContactRoute
  DonateRoute: typeof DonateRoute
  EventsRoute: typeof EventsRouteWithChildren
  FaqRoute: typeof FaqRoute
  ImpactRoute: typeof ImpactRoute
  JoinRoute: typeof JoinRoute
  NewsRoute: typeof NewsRoute
  PartnersRoute: typeof PartnersRoute
  TeamRoute: typeof TeamRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/team': {
      id: '/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof TeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partners': {
      id: '/partners'
      path: '/partners'
      fullPath: '/partners'
      preLoaderRoute: typeof PartnersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news': {
      id: '/news'
      path: '/news'
      fullPath: '/news'
      preLoaderRoute: typeof NewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join': {
      id: '/join'
      path: '/join'
      fullPath: '/join'
      preLoaderRoute: typeof JoinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/impact': {
      id: '/impact'
      path: '/impact'
      fullPath: '/impact'
      preLoaderRoute: typeof ImpactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/donate': {
      id: '/donate'
      path: '/donate'
      fullPath: '/donate'
      preLoaderRoute: typeof DonateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/causes': {
      id: '/causes'
      path: '/causes'
      fullPath: '/causes'
      preLoaderRoute: typeof CausesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/$slug': {
      id: '/events/$slug'
      path: '/$slug'
      fullPath: '/events/$slug'
      preLoaderRoute: typeof EventsSlugRouteImport
      parentRoute: typeof EventsRoute
    }
    '/causes/$slug': {
      id: '/causes/$slug'
      path: '/$slug'
      fullPath: '/causes/$slug'
      preLoaderRoute: typeof CausesSlugRouteImport
      parentRoute: typeof CausesRoute
    }
  }
}

interface CausesRouteChildren {
  CausesSlugRoute: typeof CausesSlugRoute
}

const CausesRouteChildren: CausesRouteChildren = {
  CausesSlugRoute: CausesSlugRoute,
}

const CausesRouteWithChildren =
  CausesRoute._addFileChildren(CausesRouteChildren)

interface EventsRouteChildren {
  EventsSlugRoute: typeof EventsSlugRoute
}

const EventsRouteChildren: EventsRouteChildren = {
  EventsSlugRoute: EventsSlugRoute,
}

const EventsRouteWithChildren =
  EventsRoute._addFileChildren(EventsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  CausesRoute: CausesRouteWithChildren,
  ContactRoute: ContactRoute,
  DonateRoute: DonateRoute,
  EventsRoute: EventsRouteWithChildren,
  FaqRoute: FaqRoute,
  ImpactRoute: ImpactRoute,
  JoinRoute: JoinRoute,
  NewsRoute: NewsRoute,
  PartnersRoute: PartnersRoute,
  TeamRoute: TeamRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
